"""initial schema

Revision ID: f96fd0b1ba49
Revises: 
Create Date: 2026-06-10 13:30:56.272546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96fd0b1ba49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_year', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_campaign_year'), ['campaign_year'], unique=True)

    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('partner_type', sa.String(length=120), nullable=True),
    sa.Column('address_1', sa.String(length=255), nullable=True),
    sa.Column('address_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('postal_code', sa.String(length=40), nullable=True),
    sa.Column('email_main', sa.String(length=255), nullable=True),
    sa.Column('phone_main', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('partner_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_partner_name'), ['partner_name'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('middle_initial', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('preferred_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile_phone', sa.String(length=50), nullable=True),
    sa.Column('other_phone', sa.String(length=50), nullable=True),
    sa.Column('committee_role', sa.String(length=120), nullable=True),
    sa.Column('person_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_category_mrpoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('partner_category', sa.String(length=120), nullable=False),
    sa.Column('mrpoc_person_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['mrpoc_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'partner_category', name='uq_campaign_category_mrpoc_campaign_category')
    )
    with op.batch_alter_table('campaign_category_mrpoc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_category_mrpoc_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_category_mrpoc_mrpoc_person_id'), ['mrpoc_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_category_mrpoc_partner_category'), ['partner_category'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('middle_initial', sa.String(length=1), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_partner_id'), ['partner_id'], unique=False)

    op.create_table('solicitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('solicitor_person_id', sa.Integer(), nullable=True),
    sa.Column('mrpoc_person_id', sa.Integer(), nullable=True),
    sa.Column('tranche', sa.Integer(), server_default='1', nullable=False),
    sa.Column('business_volume', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_requested', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_received', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='not_contacted', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('not_contacted', 'contacted', 'responded', 'donated', 'declined', 'closed')", name='ck_solicitation_status'),
    sa.CheckConstraint('tranche IN (1, 2, 3)', name='ck_solicitation_tranche'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['mrpoc_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['solicitor_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'campaign_id', name='uq_solicitation_partner_campaign')
    )
    with op.batch_alter_table('solicitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitations_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitations_mrpoc_person_id'), ['mrpoc_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitations_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitations_solicitor_person_id'), ['solicitor_person_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='reader', nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('person_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('solicitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitations_solicitor_person_id'))
        batch_op.drop_index(batch_op.f('ix_solicitations_partner_id'))
        batch_op.drop_index(batch_op.f('ix_solicitations_mrpoc_person_id'))
        batch_op.drop_index(batch_op.f('ix_solicitations_campaign_id'))

    op.drop_table('solicitations')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_partner_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('campaign_category_mrpoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_category_mrpoc_partner_category'))
        batch_op.drop_index(batch_op.f('ix_campaign_category_mrpoc_mrpoc_person_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_category_mrpoc_campaign_id'))

    op.drop_table('campaign_category_mrpoc')
    op.drop_table('persons')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_partner_name'))

    op.drop_table('partners')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_campaign_year'))

    op.drop_table('campaigns')
    # ### end Alembic commands ###
